//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/App/DebugInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace DGAIZone.App
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/App/DebugInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @DebugInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @DebugInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""DebugInputActions"",
    ""maps"": [
        {
            ""name"": ""Debug"",
            ""id"": ""29baba13-1f29-4315-8fef-23810bd829bb"",
            ""actions"": [
                {
                    ""name"": ""SimulateActionCard"",
                    ""type"": ""Button"",
                    ""id"": ""6300a8ee-c74b-47be-8245-5f68fcb2235b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SimulateControlCard"",
                    ""type"": ""Button"",
                    ""id"": ""d75493f4-7bd0-4330-849a-146fc48856e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SimulateLogicCard"",
                    ""type"": ""Button"",
                    ""id"": ""ecaeca86-73cf-458c-aa5f-bb9eeb7f8639"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SimulateFunctionCard"",
                    ""type"": ""Button"",
                    ""id"": ""e70de4ff-9c8e-42fb-81a9-0b0e788020d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayLevel4Simulation"",
                    ""type"": ""Button"",
                    ""id"": ""82944c52-d016-4dcc-8609-0f3a3bd3236d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnlockAllLevels"",
                    ""type"": ""Button"",
                    ""id"": ""1c7e67be-b142-45b5-b7b8-1ce7bf593ab8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5466a830-03de-49d2-8fe6-92d5aa6f6c51"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SimulateActionCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f82b472a-5a09-464b-a2ac-6fb6d0da5d61"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SimulateControlCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2797ece3-f112-4e38-a382-c66b931ca87a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SimulateLogicCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c9d2407-eff0-4600-bb9a-2cd0d9ebffa0"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SimulateFunctionCard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ba9893c-029d-4e71-a214-204fb15d48e3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayLevel4Simulation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26dfeb7e-de54-48f2-94ae-f3e7716ea124"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnlockAllLevels"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Debug
            m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
            m_Debug_SimulateActionCard = m_Debug.FindAction("SimulateActionCard", throwIfNotFound: true);
            m_Debug_SimulateControlCard = m_Debug.FindAction("SimulateControlCard", throwIfNotFound: true);
            m_Debug_SimulateLogicCard = m_Debug.FindAction("SimulateLogicCard", throwIfNotFound: true);
            m_Debug_SimulateFunctionCard = m_Debug.FindAction("SimulateFunctionCard", throwIfNotFound: true);
            m_Debug_PlayLevel4Simulation = m_Debug.FindAction("PlayLevel4Simulation", throwIfNotFound: true);
            m_Debug_UnlockAllLevels = m_Debug.FindAction("UnlockAllLevels", throwIfNotFound: true);
        }

        ~@DebugInputActions()
        {
            UnityEngine.Debug.Assert(!m_Debug.enabled, "This will cause a leak and performance issues, DebugInputActions.Debug.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Debug
        private readonly InputActionMap m_Debug;
        private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
        private readonly InputAction m_Debug_SimulateActionCard;
        private readonly InputAction m_Debug_SimulateControlCard;
        private readonly InputAction m_Debug_SimulateLogicCard;
        private readonly InputAction m_Debug_SimulateFunctionCard;
        private readonly InputAction m_Debug_PlayLevel4Simulation;
        private readonly InputAction m_Debug_UnlockAllLevels;
        /// <summary>
        /// Provides access to input actions defined in input action map "Debug".
        /// </summary>
        public struct DebugActions
        {
            private @DebugInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public DebugActions(@DebugInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Debug/SimulateActionCard".
            /// </summary>
            public InputAction @SimulateActionCard => m_Wrapper.m_Debug_SimulateActionCard;
            /// <summary>
            /// Provides access to the underlying input action "Debug/SimulateControlCard".
            /// </summary>
            public InputAction @SimulateControlCard => m_Wrapper.m_Debug_SimulateControlCard;
            /// <summary>
            /// Provides access to the underlying input action "Debug/SimulateLogicCard".
            /// </summary>
            public InputAction @SimulateLogicCard => m_Wrapper.m_Debug_SimulateLogicCard;
            /// <summary>
            /// Provides access to the underlying input action "Debug/SimulateFunctionCard".
            /// </summary>
            public InputAction @SimulateFunctionCard => m_Wrapper.m_Debug_SimulateFunctionCard;
            /// <summary>
            /// Provides access to the underlying input action "Debug/PlayLevel4Simulation".
            /// </summary>
            public InputAction @PlayLevel4Simulation => m_Wrapper.m_Debug_PlayLevel4Simulation;
            /// <summary>
            /// Provides access to the underlying input action "Debug/UnlockAllLevels".
            /// </summary>
            public InputAction @UnlockAllLevels => m_Wrapper.m_Debug_UnlockAllLevels;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Debug; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="DebugActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="DebugActions" />
            public void AddCallbacks(IDebugActions instance)
            {
                if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
                @SimulateActionCard.started += instance.OnSimulateActionCard;
                @SimulateActionCard.performed += instance.OnSimulateActionCard;
                @SimulateActionCard.canceled += instance.OnSimulateActionCard;
                @SimulateControlCard.started += instance.OnSimulateControlCard;
                @SimulateControlCard.performed += instance.OnSimulateControlCard;
                @SimulateControlCard.canceled += instance.OnSimulateControlCard;
                @SimulateLogicCard.started += instance.OnSimulateLogicCard;
                @SimulateLogicCard.performed += instance.OnSimulateLogicCard;
                @SimulateLogicCard.canceled += instance.OnSimulateLogicCard;
                @SimulateFunctionCard.started += instance.OnSimulateFunctionCard;
                @SimulateFunctionCard.performed += instance.OnSimulateFunctionCard;
                @SimulateFunctionCard.canceled += instance.OnSimulateFunctionCard;
                @PlayLevel4Simulation.started += instance.OnPlayLevel4Simulation;
                @PlayLevel4Simulation.performed += instance.OnPlayLevel4Simulation;
                @PlayLevel4Simulation.canceled += instance.OnPlayLevel4Simulation;
                @UnlockAllLevels.started += instance.OnUnlockAllLevels;
                @UnlockAllLevels.performed += instance.OnUnlockAllLevels;
                @UnlockAllLevels.canceled += instance.OnUnlockAllLevels;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="DebugActions" />
            private void UnregisterCallbacks(IDebugActions instance)
            {
                @SimulateActionCard.started -= instance.OnSimulateActionCard;
                @SimulateActionCard.performed -= instance.OnSimulateActionCard;
                @SimulateActionCard.canceled -= instance.OnSimulateActionCard;
                @SimulateControlCard.started -= instance.OnSimulateControlCard;
                @SimulateControlCard.performed -= instance.OnSimulateControlCard;
                @SimulateControlCard.canceled -= instance.OnSimulateControlCard;
                @SimulateLogicCard.started -= instance.OnSimulateLogicCard;
                @SimulateLogicCard.performed -= instance.OnSimulateLogicCard;
                @SimulateLogicCard.canceled -= instance.OnSimulateLogicCard;
                @SimulateFunctionCard.started -= instance.OnSimulateFunctionCard;
                @SimulateFunctionCard.performed -= instance.OnSimulateFunctionCard;
                @SimulateFunctionCard.canceled -= instance.OnSimulateFunctionCard;
                @PlayLevel4Simulation.started -= instance.OnPlayLevel4Simulation;
                @PlayLevel4Simulation.performed -= instance.OnPlayLevel4Simulation;
                @PlayLevel4Simulation.canceled -= instance.OnPlayLevel4Simulation;
                @UnlockAllLevels.started -= instance.OnUnlockAllLevels;
                @UnlockAllLevels.performed -= instance.OnUnlockAllLevels;
                @UnlockAllLevels.canceled -= instance.OnUnlockAllLevels;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DebugActions.UnregisterCallbacks(IDebugActions)" />.
            /// </summary>
            /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
            public void RemoveCallbacks(IDebugActions instance)
            {
                if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
            /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
            /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
            public void SetCallbacks(IDebugActions instance)
            {
                foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="DebugActions" /> instance referencing this action map.
        /// </summary>
        public DebugActions @Debug => new DebugActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Debug" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
        /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
        public interface IDebugActions
        {
            /// <summary>
            /// Method invoked when associated input action "SimulateActionCard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSimulateActionCard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SimulateControlCard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSimulateControlCard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SimulateLogicCard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSimulateLogicCard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SimulateFunctionCard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSimulateFunctionCard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "PlayLevel4Simulation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPlayLevel4Simulation(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "UnlockAllLevels" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnUnlockAllLevels(InputAction.CallbackContext context);
        }
    }
}
